version: '2'

services:
  json-server:
    build:
      context: .
      dockerfile: infra/json-server/Dockerfile
    container_name: json-server
    ports:
      - "3000:3000"
    volumes:
      - /infra/json-server/data/:/data/
      
  # todo-app:
  #   build:
  #     context: .
  #     dockerfile: src/Dockerfile
  #   container_name: todo-app
  #   ports:
  #     - "3001:3000"
