name: 'coverage'
on:
  pull_request:
    branches:
    - main

jobs:
    coverage:
        runs-on: ubuntu-latest
        name: Coverage report
        needs: docker
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Test coverage
              uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                  output: report-markdown
                  annotations: failed-tests
                  test-script: npm run coverage               
# jobs:
#   coverage:
#     runs-on: ubuntu-latest
#     name: Coverage report
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2
#       - name: Test coverage
#         uses: ArtiomTr/jest-coverage-report-action@v2
#         with:
#           annotations: failed-tests
#           test-script: npm run test:badges
#       - name: Generating coverage badges
#         uses: jpb06/jest-badges-action@latest
#         with:
#           branches: main,develop
#           coverage-summary-path: ./coverage/coverage-summary.json

#   update-coverage-in-readme:
#     name: Update Coverage in README
#     needs: coverage
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - name: Jest Coverage Comment
#         id: coverageComment
#         uses: MishaKav/jest-coverage-comment@main
#         with:
#           hide-comment: true
#           coverage-summary-path: ./coverage/coverage-summary.json

#       - name: Check the output coverage
#         run: |
#           echo "pwd print" $pwd
#           echo "Coverage Percentage - ${{ steps.coverageComment.outputs.coverage }}"
#           echo "Coverage Color - ${{ steps.coverageComment.outputs.color }}"
#           echo "Summary HTML - ${{ steps.coverageComment.outputs.summaryHtml }}"

#       - name: Create the badge
#         if: github.ref == 'refs/heads/main'
#         uses: schneegans/dynamic-badges-action@v1.6.0
#         with:
#           auth: ${{ secrets.JEST_COVERAGE_COMMENT }}
#           gistID: 5e90d640f8c212ab7bbac38f72323f80
#           filename: jest-coverage-comment__main.json
#           label: Coverage
#           message: ${{ steps.coverageComment.outputs.coverage }}%
#           color: ${{ steps.coverageComment.outputs.color }}
#           namedLogo: javascript
