name: 'coverage'
on:
  pull_request:
    branches:
    - main

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Start Infrastructure
      run:  docker-compose -f docker-compose.yml up --build --force-recreate -d   

    coverage:
        runs-on: ubuntu-latest
        name: Coverage report
        needs: docker
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Test coverage
              uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                  output: report-markdown
                  annotations: failed-tests
                  test-script: npm run coverage               